# Config file for automatic testing at travis-ci.com
sudo: false
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"
  - "pypy3"

# Command to run tests, e.g. python setup.py test
script: python -m unittest
